### ISSUE TITLE
Lock the vehicle when reaching a pre-determined rank 

### ISSUE THREAD

**Issue by qweras465** [VenomXNL/XNLRankBar#5]
welcome
I want to lock a vehicle and no one can buy it from the vehicle shop until it reaches a certain rank that has been set before

**Comment by VenomXNL** [comment]
People, for the love of god: READ THE DOCUMENTATION,

And if you have questions (in regards of developing your OWN addon or level system): Use the FiveM Forum.

Honestly it's all kinds of 'requests' of people opening issuess on this resource while they are not even reading the documentation:

THIS RESOURCE DOES NOT MAINTAIN LEVELS, NOR DOES IT HANDLE OR STORE THEM.
It is just an GRAPHICAL INTERFACE.
